spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.61.45:3306/springbootdemo?characterEncoding=utf8&useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
    username: fulsun
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    druid:
      # 初始化大小，最小或最大
      initial-size: 5
      max-active: 20
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。在mysql下建议关闭。 PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      poolPreparedStatements: false
      #要启用PSCache，-1为关闭 必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true  可以把这个数值配置大一些，比如说100
      maxOpenPreparedStatements: -1
        #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
#      stat-view-servlet:
#        # 是否开启监控页面，，为了安全起见1.1.10后默认为关闭
#        enabled: true
#        login-username: druid
#        login-password: druid
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    # #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
---
spring:
  profiles: dev
## 日志级别
logging:
  level:
    top:
      fulsun:
        mapper: debug

mybatis:
  type-aliases-package: top.fulsun.entity
  ## 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  # check-config-location: true
  ## 配置文件位置
  # config-location: classpath:mybatis/mybatis-config.xml
  ## mapper xml文件地址
  # mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    ## 开启mybatis驼峰命名映射，不然取得时间的值为空-->
    map-underscore-to-camel-case: true
server:
  port: 8080



---
spring:
  profiles: test
server:
  port: 9000